global:
  imageRegistry: ""
  imagePullSecrets:
    - name: prod-registry-secret

backend:
  replicaCount: 3

  image:
    tag: "v1.0.0"
    pullPolicy: IfNotPresent

  env:
    NODE_ENV: production
    LOG_LEVEL: "warn"
    ENABLE_SWAGGER: "false"
    CORS_ORIGIN: "https://mieszkaniownik.wsparcie.dev,https://app.mieszkaniownik.wsparcie.dev"

  resources:
    requests:
      cpu: 200m
      memory: 512Mi
    limits:
      cpu: 1000m
      memory: 1Gi

postgresql:
  enabled: true
  primary:
    persistence:
      enabled: true
      size: 20Gi
      storageClass: "ssd"
    resources:
      requests:
        cpu: 500m
        memory: 512Mi
      limits:
        cpu: 1000m
        memory: 1Gi
    service:
      annotations:
        service.beta.kubernetes.io/aws-load-balancer-internal: "true"

redis:
  enabled: true
  master:
    persistence:
      enabled: true
      size: 8Gi
      storageClass: "ssd"
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 200m
        memory: 256Mi

databaseJobs:
  migrate:
    enabled: true
  seed:
    enabled: false

secrets:
  postgresql:
    POSTGRES_PASSWORD: ""
  app:
    JWT_SECRET: ""
    GOOGLE_CLIENT_ID: ""
    GOOGLE_CLIENT_SECRET: ""
    DISCORD_WEBHOOK_URL: ""
    EMAIL_USER: ""
    EMAIL_PASS: ""

config:
  database:
    maxConnections: 20
    ssl: true
  redis:
    ttl: 7200
  scraper:
    interval: "0 */6 * * *"
    maxPages: 100
  notifications:
    discord:
      enabled: true
    email:
      enabled: true

ingress:
  enabled: true
  className: "gce"
  annotations:
    kubernetes.io/ingress.class: "gce"
    kubernetes.io/ingress.global-static-ip-name: "mieszkaniownik-ingress-ip"
    networking.gke.io/managed-certificates: "mieszkaniownik-backend-cert"
    kubernetes.io/ingress.allow-http: "true"
    cloud.google.com/neg: '{"ingress": true}'
    cloud.google.com/backend-config: "mieszkaniownik-backend-backend-config"
  hosts:
    - host: mieszkaniownik.wsparcie.dev
      paths:
        - path: /
          pathType: Prefix
          service: backend
    - host: api.mieszkaniownik.wsparcie.dev
      paths:
        - path: /
          pathType: Prefix
          service: backend
  tls: []

autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 15
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 80

podSecurityContext:
  runAsNonRoot: true
  runAsUser: 1001
  fsGroup: 1001

securityContext:
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: false
  runAsNonRoot: true
  runAsUser: 1001
  capabilities:
    drop:
      - ALL

networkPolicy:
  enabled: true

cronJobs:
  fullSync:
    enabled: true
    schedule: "0 2 * * *"
    suspend: false
    resources:
      requests:
        cpu: 1000m
        memory: 2Gi
      limits:
        cpu: 4000m
        memory: 4Gi
  
  cleanup:
    enabled: true
    schedule: "0 4 * * 0"
    suspend: false

backendConfig:
  enabled: true
  cdn:
    enabled: true
    cachePolicy:
      includeHost: true
      includeProtocol: true
      includeQueryString: false
    negativeCaching: true
  sessionAffinity:
    affinityType: "CLIENT_IP"
    affinityCookieTtlSec: 3600
